# Generated by Django 4.0.6 on 2023-01-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_courses_options_courses_featured_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='tech',
            new_name='techs',
        ),
    ]
