# Generated by Django 4.0.6 on 2023-01-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_tech_courses_techs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='Category',
            new_name='category',
        ),
    ]
