# Generated by Django 4.0.6 on 2023-01-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_category_courses_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2.Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '3.students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '1.Teachers'},
        ),
    ]
