# Generated by Django 4.1.4 on 2023-01-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_coursecategory_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '4.students'},
        ),
    ]
