# Generated by Django 4.0.6 on 2023-12-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_teacher_detail_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='interseted_categroies',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
