# Generated by Django 4.0.6 on 2024-01-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_address_student_interseted_categroies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='interseted_categroies',
            new_name='interested_categories',
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_time', models.DateTimeField(auto_now_add=True)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='main.student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='main.courses')),
            ],
            options={
                'verbose_name_plural': '6.Enrolled Courses',
            },
        ),
    ]
